"""Real-cadwork integration harness for model-aware versioning (US-6).

Host-only: copies the timber fixture, writes a run-program wrapper with a baked
result path, launches via ``ProcessLauncher`` / CLI translation
(``--run-program`` + ``--no-gui``), and asserts the result JSON sidecar.

``ci_start.exe`` hands off to cadwork and returns immediately
(``docs/terminal.md``), so the host **polls** the result sidecar rather than
treating the launcher exit code as completion.

Skips when ``ci_start`` or git/GitPython is unavailable so default CI stays green.
"""

from __future__ import annotations

import json
import shutil
import tempfile
import textwrap
import time
import uuid
from pathlib import Path

import pytest

from pycadwork.terminal.cli import main as cadwork_main
from pycadwork.terminal.launcher import (
    ExecutableNotFoundError,
    ProcessLauncher,
    SubprocessLauncher,
    find_ci_start,
)
from pycadwork.versioning import is_git_available

FIXTURE = (
    Path(__file__).resolve().parents[1] / "fixtures" / "model" / "timber-framed-slab.3d"
)
SCRIPT_SOURCE = Path(__file__).resolve().parent / "_cadwork_it_script.py"
FEATURE_BRANCH = "feature/it"
#: Cadwork cold-start + commit/branch/smart-switch is typically ~60–90s here.
RESULT_WAIT_S = 300
RESULT_POLL_S = 1.0


def _ci_start_available() -> bool:
    try:
        find_ci_start()
        return True
    except ExecutableNotFoundError:
        return False


_SKIP_REASON = "ci_start.exe or git/GitPython unavailable"
pytestmark = pytest.mark.skipif(
    not (_ci_start_available() and is_git_available()),
    reason=_SKIP_REASON,
)


def _short_work_dir() -> Path:
    """Prefer a short ``%TEMP%\\cwit-<id>`` path over deep pytest tmp trees.

    Cadwork + git have been more reliable on short absolute paths in practice.
    """
    root = Path(tempfile.gettempdir()) / f"cwit-{uuid.uuid4().hex[:8]}"
    root.mkdir(parents=True, exist_ok=True)
    return root


def _write_run_program(work: Path, result_path: Path) -> Path:
    """Copy the IT body and a thin entry wrapper with a baked result path.

    Cadwork's embedded interpreter does not reliably inherit host environment
    variables, so the result path is inlined into the wrapper rather than
    passed via env.
    """
    body = work / "_cadwork_it_script.py"
    shutil.copy2(SCRIPT_SOURCE, body)
    entry = work / "run_program.py"
    result_literal = str(result_path.resolve())
    body_dir = str(body.parent.resolve())
    entry.write_text(
        textwrap.dedent(
            f"""\
            # Auto-generated by test_cadwork_run_program — do not edit.
            import json
            import sys
            import traceback
            from pathlib import Path

            _here = Path(r"{body_dir}")
            if str(_here) not in sys.path:
                sys.path.insert(0, str(_here))

            _result = Path(r"{result_literal}")
            try:
                import _cadwork_it_script as _it
                raise SystemExit(_it.main(str(_result)))
            except SystemExit:
                raise
            except Exception as exc:
                _result.write_text(
                    json.dumps(
                        {{
                            "ok": False,
                            "error": f"{{type(exc).__name__}}: {{exc}}",
                            "traceback": traceback.format_exc(),
                        }},
                        indent=2,
                        sort_keys=True,
                    )
                    + "\\n",
                    encoding="utf-8",
                )
                raise SystemExit(1) from exc
            """
        ),
        encoding="utf-8",
    )
    return entry


def _wait_for_result(result_path: Path, timeout_s: float = RESULT_WAIT_S) -> dict:
    """Poll until the sidecar exists and is valid JSON, or time out."""
    deadline = time.monotonic() + timeout_s
    last_error: str | None = None
    while time.monotonic() < deadline:
        if result_path.is_file():
            try:
                text = result_path.read_text(encoding="utf-8")
                if text.strip():
                    return json.loads(text)
            except (OSError, json.JSONDecodeError) as exc:
                # Partial write while cadwork is still flushing.
                last_error = str(exc)
        time.sleep(RESULT_POLL_S)
    detail = f" last read error: {last_error}" if last_error else ""
    raise AssertionError(
        f"run-program did not produce a result sidecar at {result_path} "
        f"within {timeout_s}s.{detail} Ensure pycadwork is provisioned into "
        "cadwork (scripts/Install-PycadworkRuntime.ps1) and git is available "
        "in cadwork's interpreter."
    )


def test_cadwork_run_program_commit_branch_edit_checkout() -> None:
    """Launch fixture via run-program; assert model-aware switch-back result JSON."""
    assert FIXTURE.is_file(), f"missing fixture model: {FIXTURE}"
    assert SCRIPT_SOURCE.is_file(), f"missing run-program body: {SCRIPT_SOURCE}"

    work = _short_work_dir()
    try:
        model = work / FIXTURE.name
        shutil.copy2(FIXTURE, model)

        result_path = work / "it-result.json"
        script = _write_run_program(work, result_path)

        launcher: ProcessLauncher = SubprocessLauncher()
        # Exit code of ci_start is not completion — it hands off immediately.
        cadwork_main(
            [
                "open",
                str(model),
                "--run-program",
                str(script),
                "--no-gui",
            ],
            launcher=launcher,
        )

        payload = _wait_for_result(result_path)
        assert payload.get("ok") is True, payload
        assert payload.get("feature_branch") == FEATURE_BRANCH
        assert payload.get("markers_on_feature", 0) >= 1
        assert payload.get("markers_after_checkout") == 0
        assert payload.get("apply_to_model_default") is True
    finally:
        # Best-effort cleanup; cadwork may still hold the model briefly.
        shutil.rmtree(work, ignore_errors=True)
