"""pycadwork: OOP layer over cwapi3d (cadwork 3D Python API).

The top-level namespace re-exports the public surface so callers can write
``from pycadwork import Beam, Wall, CoverBuilder, Point3D`` without knowing
the submodule layout. All cwapi3d interaction is funnelled through one
internal seam (``pycadwork.cadwork_adapter``); the rest of the package is
agnostic to any specific cwapi3d version.
"""

from __future__ import annotations

from pycadwork.building import (
    BuildingName,
    Storey,
    StoreyAssigner,
    StoreyAssignment,
    StoreyName,
    StoreyStack,
)
from pycadwork.cadwork_adapter.types import CoverKind, GroupingMode
from pycadwork.connectivity import (
    ConnectionGraph,
    build_connection_graph,
    find_connected,
)
from pycadwork.document import Document, ProjectInfo
from pycadwork.element import (
    REGISTRY,
    AuxiliaryElement,
    Beam,
    CircularMep,
    ConnectorAxis,
    Container,
    CrossSection,
    Drilling,
    Element,
    ElementRegistry,
    Line,
    LinearElement,
    Node,
    Opening,
    OrientedElement,
    Plate,
    RectangularMep,
    Surface,
    discover_containers,
    from_id,
    parent_container,
    register_element,
)
from pycadwork.element.cover import (
    Aggregate,
    CoverAssigner,
    CoverAssignment,
    CoverBuilder,
    Group,
    Roof,
    Slab,
    Wall,
    discover_covers,
)
from pycadwork.geometry import (
    AxisAlignedBoundingBox,
    AxisFrame,
    AxisPoints,
    Brep,
    Face,
    Frame3D,
    Loop,
    OrientedBoundingBox,
    PanelSection,
    Plane3D,
    Point3D,
    RTreeIndex3D,
    RectSection,
    Segment,
    SpatialIndex3D,
    SpatialQuery3D,
    Vector3D,
)
from pycadwork.persistence import (
    AttributeRecord,
    BuildingRecord,
    ContainerMemberRecord,
    CoverRecord,
    ElementRecord,
    GatewayConnection,
    GeometryRecord,
    ModelSnapshot,
    ProjectRecord,
    SqliteConnection,
    StoreyAssignmentRecord,
    StoreyRecord,
    SyncReport,
    Synchronizer,
    UserAttributeRecord,
    open_sqlite,
)
from pycadwork.utility import (
    DisplayRefreshScope,
    auto_eq,
    auto_hash,
    auto_recreate,
    auto_repr,
    batch_apply,
    deprecated,
    suppressed_display,
)

__all__ = [
    "REGISTRY",
    "Aggregate",
    "AttributeRecord",
    "AuxiliaryElement",
    "AxisAlignedBoundingBox",
    "AxisFrame",
    "AxisPoints",
    "Beam",
    "Brep",
    "BuildingName",
    "BuildingRecord",
    "CircularMep",
    "ConnectionGraph",
    "ConnectorAxis",
    "Container",
    "ContainerMemberRecord",
    "CoverAssigner",
    "CoverAssignment",
    "CoverBuilder",
    "CoverKind",
    "CoverRecord",
    "CrossSection",
    "DisplayRefreshScope",
    "Document",
    "Drilling",
    "Element",
    "ElementRecord",
    "ElementRegistry",
    "Face",
    "Frame3D",
    "GatewayConnection",
    "GeometryRecord",
    "Group",
    "GroupingMode",
    "Line",
    "LinearElement",
    "Loop",
    "ModelSnapshot",
    "Node",
    "Opening",
    "OrientedBoundingBox",
    "OrientedElement",
    "PanelSection",
    "Plane3D",
    "Plate",
    "Point3D",
    "ProjectInfo",
    "ProjectRecord",
    "RTreeIndex3D",
    "RectSection",
    "RectangularMep",
    "Roof",
    "Segment",
    "Slab",
    "SpatialIndex3D",
    "SpatialQuery3D",
    "SqliteConnection",
    "Storey",
    "StoreyAssigner",
    "StoreyAssignment",
    "StoreyAssignmentRecord",
    "StoreyName",
    "StoreyRecord",
    "StoreyStack",
    "Surface",
    "SyncReport",
    "Synchronizer",
    "UserAttributeRecord",
    "Vector3D",
    "Wall",
    "auto_eq",
    "auto_hash",
    "auto_recreate",
    "auto_repr",
    "batch_apply",
    "build_connection_graph",
    "deprecated",
    "discover_containers",
    "discover_covers",
    "find_connected",
    "from_id",
    "open_sqlite",
    "parent_container",
    "register_element",
    "suppressed_display",
]
